# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'


platform :ios, '10.0'

# Override Firebase SDK Version
$FirebaseSDKVersion = '8.5.0'
# $RNFirebaseAsStaticFramework = true# add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
# Add the pod for Firebase Cloud Messaging
pod 'Firebase/Messaging'
# pod 'ReactCommon/callinvoker'
# pod 'React-callinvoker'
# # or pod ‘Firebase/AnalyticsWithoutAdIdSupport’
# for Analytics without IDFA collection capability



target 'Rider' do
  # Comment the next line if you don't want to use dynamic frameworks
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  # Pods for Rider


  target 'RiderTests' do
    inherit! :complete
    # Pods for testing
  end



# use_flipper!({ 'Flipper-Folly' => '2.5' })
use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.3.1' })
post_install do |installer|
   flipper_post_install(installer)
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
        # config.build_settings["ONLY_ACTIVE_ARCH"] = "NO"
    end
end

end
end

target 'Rider-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Rider-tvOS

  target 'Rider-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

# post_install do |installer|
#   installer.pods_project.targets.each do |target|
#     target.build_configurations.each do |config|
#       config.build_settings["ONLY_ACTIVE_ARCH"] = "NO"
#     end
#   end
# end

# global code  hear

